### ISSUE TITLE
[BUG] Can't download anything, crashes

### ISSUE THREAD

**Issue by dgudim** [deniscerri/ytdlnis#224]
Trying to download anything either from the app directly or from the flyout crashes the app

```
FATAL EXCEPTION: DefaultDispatcher-worker-3
Process: com.deniscerri.ytdl, PID: 19332
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BOOLEAN at line 1 column 101 path $.g
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source:69)
	at com.google.gson.Gson.fromJson(Unknown Source:20)
	at com.google.gson.Gson.fromJson(Unknown Source:4)
	at com.google.gson.Gson.fromJson(Unknown Source:9)
	at com.google.gson.Gson.fromJson(Unknown Source:0)
	at s1.a.j(Unknown Source:12)
	at t1.f.r(Unknown Source:481)
	at v1.c.f(Unknown Source:2)
	at w1.c$h.w(Unknown Source:193)
	at v7.a.i(Unknown Source:11)
	at n8.w0.run(Unknown Source:88)
	at kotlinx.coroutines.internal.k.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.k.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.O(Unknown Source:0)
	at kotlinx.coroutines.scheduling.a$c.d(Unknown Source:14)
	at kotlinx.coroutines.scheduling.a$c.n(Unknown Source:28)
	at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
	Suppressed: n8.u0: [n2{Cancelling}@fe06de6, Dispatchers.IO]
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BOOLEAN at line 1 column 101 path $.g
	at com.google.gson.stream.JsonReader.beginArray(Unknown Source:56)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source:21)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Unknown Source:0)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Unknown Source:2)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source:47)
	... 16 more
```

**Comment by dgudim** [comment]
Yes, I have tried reinstalling, clearing the data, updating yt-dl

**Comment by deniscerri** [comment]
What version are you at. Can you try one of the betas in the telegram group?

**Comment by dgudim** [comment]
I am on 1.6.3

**Comment by dgudim** [comment]
Tried the 1.6.3.12 It works. Thanks!
