### ISSUE TITLE
[BUG] App crashes at launch

### ISSUE THREAD

**Issue by HeroGalak** [deniscerri/ytdlnis#243]
**Describe the bug**
YTDLnis sometimes crashes at start.
The app stays opened for a fraction of a second, then it crashes. After that Android detect the crash and asks to delete cache to try solving the issue.

**To Reproduce**
It happens randomly when launching app, cannot predict when it will crash. It happens every 1/2 days

**System Info**
 - Android Version: Android 13
 - App Version: 1.6.4 (Fdroid)
 - Other Device Information: Samsung A52s 5G

**Logs of the crash**

`FATAL EXCEPTION: main
Process: com.deniscerri.ytdl, PID: 20805
java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=1 shortcut=null contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
 at android.app.NotificationManager.fixNotification(NotificationManager.java:719)
 at android.app.NotificationManager.notifyAsUser(NotificationManager.java:698)
 at android.app.NotificationManager.notify(NotificationManager.java:632)
 at android.app.NotificationManager.notify(NotificationManager.java:608)
 at t4.d.run(Unknown Source:8)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8757)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

**Comment by deniscerri** [comment]
I believe this is an issue with the yt-dlp auto updater
turn it off for now until i launch the next version

**Comment by deniscerri** [comment]
[Try the new release](https://github.com/deniscerri/ytdlnis/releases/tag/v1.6.5)
