### ISSUE TITLE
Report bug

### ISSUE THREAD

**Issue by libea18** [deniscerri/ytdlnis#27]
I got crash
I downloaded tiktok video and when i wanna play that after download :

java.lang.IllegalArgumentException: Failed to find configured root that contains /
	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:825)
	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:450)
	at com.deniscerri.ytdlnis.page.DownloadsFragment.openFileIntent(DownloadsFragment.java:672)
	at com.deniscerri.ytdlnis.page.DownloadsFragment.onClick(DownloadsFragment.java:569)
	at android.view.View.performClick(View.java:6608)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1219)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25921)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by deniscerri** [comment]
Can you please give me the link you used? Thanks

**Comment by deniscerri** [comment]
Closing this due to inactivity
