### ISSUE TITLE
[BUG] Ytdlnis crashed.

### ISSUE THREAD

**Issue by NikunjKhangwal** [deniscerri/ytdlnis#344]
** Before making an issue make sure you are using the latest version of yt-dlp in the settings. Perhaps try using the nightly version of yt-dlp. If that didn't help, proceed with the issue

**Describe the bug**
The app randomly crashes sometimes

**To Reproduce**
Sharing a video from youtube to download

**Expected behavior**
The app should show the download window normally.

**(please complete the following information):**
 - Android Version: 12
 - App Version: 1.6.9
 - Other Device Information: Redmi 9/Helio G80

**Additional context**

Here are two crash logs from Logfox:

FATAL EXCEPTION: DefaultDispatcher-worker-3
Process: com.deniscerri.ytdl, PID: 20198
androidx.startup.StartupException: Exception in completion handler InvokeOnCompletion@9d8a5a[job@ed7848b] for StandaloneCoroutine{Completed}@ed7848b
	at kotlinx.coroutines.JobSupport.completeStateFinalization(SourceFile:138)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(SourceFile:162)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(SourceFile:222)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(SourceFile:5)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:32)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at androidx.work.Worker$2.run(SourceFile:960)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:99)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Completed}@ed7848b, Dispatchers.IO]
Caused by: java.lang.IllegalStateException: Fragment DownloadBottomSheetDialog{fa9da05} (e5714ccc-7938-42ee-a3d6-54d2cde4d471) not attached to an activity.
	at androidx.fragment.app.Fragment.requireActivity(SourceFile:18)
	at com.deniscerri.ytdlnis.ui.downloadcard.DownloadBottomSheetDialog$initUpdateData$2.invoke(SourceFile:2)
	at com.deniscerri.ytdlnis.ui.downloadcard.DownloadBottomSheetDialog$initUpdateData$2.invoke(SourceFile:1)
	at kotlinx.coroutines.InvokeOnCompletion.invoke(SourceFile:7)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(SourceFile:107)
	... 9 more

Second:-

FATAL EXCEPTION: DefaultDispatcher-worker-6
Process: com.deniscerri.ytdl, PID: 28690
java.lang.IllegalArgumentException: /storage/emulated/0/Video/YG ENTERTAINMENT - BABYMONSTER ( does not exist
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:255)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:355)
	at com.deniscerri.ytdlnis.util.Extensions.getMediaDuration(Unknown Source:31)
	at com.deniscerri.ytdlnis.work.DownloadWorker$doWork$3$emit$4$1$4$1.invokeSuspend(SourceFile:869)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:159)
	at kotlin.UnsignedKt.runBlocking(SourceFile:101)
	at kotlin.UnsignedKt.runBlocking$default(SourceFile:3)
	at com.deniscerri.ytdlnis.work.DownloadWorker$doWork$3$emit$4$1.invokeSuspend(SourceFile:647)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:109)
	at androidx.work.Worker$2.run(SourceFile:960)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:99)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b7718bf, Dispatchers.IO]

**Comment by zaednasr** [comment]
Both errors i believe have been resolved now. Might make a quick small release in the weekend

**Comment by YuenSzeHong** [comment]
when will this be released, i am suffering from the same crashing

**Comment by NikunjKhangwal** [comment]
I'm also patiently waiting

**Comment by tusharchopra07** [comment]
> I'm also patiently waiting

No more waiting The update will release tommorow (as the current maintainer said) 🎉

**Comment by teddysulaimanGL** [comment]
Yep, so stay tuned
