### ISSUE TITLE
[BUG] Application crashes when loading content

### ISSUE THREAD

**Issue by Articmar** [deniscerri/ytdlnis#355]
Error log: 
```
java.lang.RuntimeException: setDataSource failed: status = 0x80000000
	at android.media.MediaMetadataRetriever.setDataSource(Native Method)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:71)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:166)
	at com.deniscerri.ytdlnis.util.Extensions.getMediaDuration(SourceFile)
	at com.deniscerri.ytdlnis.work.DownloadWorker$doWork$3$emit$4$1$4$1.invokeSuspend(SourceFile:869)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:159)
	at kotlin.UnsignedKt.runBlocking(SourceFile:101)
	at kotlin.UnsignedKt.runBlocking$default(SourceFile:3)
	at com.deniscerri.ytdlnis.work.DownloadWorker$doWork$3$emit$4$1.invokeSuspend(SourceFile:647)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile)
	at androidx.work.Worker$2.run(SourceFile:960)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:99)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b628c87, Dispatchers.IO]
```

**Comment by zaednasr** [comment]
fixed in 1.7.0
