### ISSUE TITLE
[BUG] App Crash

### ISSUE THREAD

**Issue by NikunjKhangwal** [deniscerri/ytdlnis#394]
**Describe the bug**
The app randomly crashed

**To Reproduce**
I don't remember what i pressed exactly but i was switching between download section and settings

**Expected behavior**
The app shouldn't crash

 - Android Version: 12
 - App Version: 1.7.2
 - Other Device Information: Redmi 9/MIUI 13

**Additional context**
Here's the crash log:

FATAL EXCEPTION: main
Process: com.deniscerri.ytdl, PID: 1988
java.lang.IllegalArgumentException: Navigation action/destination com.deniscerri.ytdl:id/action_mainSettingsFragment_to_appearanceSettingsFragment cannot be found from the current destination FragmentNavigator$Destination(com.deniscerri.ytdl:id/appearanceSettingsFragment) label=AppearanceSettingsFragment class=com.deniscerri.ytdlnis.ui.more.settings.GeneralSettingsFragment
	at androidx.navigation.NavController.navigate(SourceFile:10)
	at com.deniscerri.ytdlnis.ui.more.settings.MainSettingsFragment.onCreatePreferences$lambda$0(SourceFile:15)
	at com.deniscerri.ytdlnis.ui.more.settings.MainSettingsFragment.$r8$lambda$G8wfJz53e8Rn_FgOizxY8Sk5SVc(SourceFile:1)
	at androidx.navigation.ui.NavigationUI$$ExternalSyntheticLambda0.onPreferenceClick(SourceFile:1)
	at androidx.preference.Preference.performClick(SourceFile:19)
	at androidx.preference.Preference$1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7751)
	at android.view.View.performClickInternal(View.java:7724)
	at android.view.View.access$3700(View.java:858)
	at android.view.View$PerformClick.run(View.java:29332)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by zaednasr** [comment]
Noted

**Comment by zaednasr** [comment]
Judging from the error you were in general settings but you tried to navigate to general again? Lol
Strange

Can you reproduce it?

**Comment by NikunjKhangwal** [comment]
Can't. I tried to go back and forth between settings and sections and double tap on general. Very strange indeed. I'll inform if i found something.

**Comment by Yunkah99** [comment]
Confirmed: tapping on the home icon crashes the app. Samsung tab s7, Android 13.

**Comment by zaednasr** [comment]
@Yunkah99 can you share the error log?

**Comment by Yunkah99** [comment]
How?

**Comment by NikunjKhangwal** [comment]
> How?

Usually your phone itself has a log viewer but if doesn't you can use [LogFox](https://github.com/F0x1d/LogFox) to record it. Run Logfox in background and press home button in ytdlnis to crash it. Logfox will collect the crash log and show you a notification. You can copy log from there and paste it.

**Comment by zaednasr** [comment]
@Yunkah99 any updates on this?

**Comment by Yunkah99** [comment]
Nope

**Comment by zaednasr** [comment]
Did the error disappear or you cant use logfox?

**Comment by zaednasr** [comment]
@Yunkah99 lmk

**Comment by zaednasr** [comment]
implemented a crash logger in the app. So when the new release comes and the app crashes, look at the logs and send it here

**Comment by NikunjKhangwal** [comment]
Sure if i can reproduce it.

**Comment by zaednasr** [comment]
check 1.7.4

**Comment by NikunjKhangwal** [comment]
A lot of users are reporting bugs so I'll wait a bit before next release
