### ISSUE TITLE
[BUG]Not found '_raw_cbc.so'

### ISSUE THREAD

**Issue by Phazeus** [deniscerri/ytdlnis#431]
Getting that bug:

 -N "2" --trim-filenames "204" --no-mtime --parse-metadata "uploader:(?P<uploader>.+)(?: - Topic)$" --parse-metadata "%(uploader,channel,creator,artist|null)s:%(uploader)s" --parse-metadata "artist:(?P<meta_album_artist>[^,]+)" --parse-metadata "%(album_artist,meta_album_artist,uploader)s:%(album_artist)s" --parse-metadata "%(release_year,release_date>%Y,upload_date>%Y)s:%(meta_date)s" --parse-metadata "%(album,title)s:%(meta_album)s" -f "140" -x -P "/data/user/0/com.deniscerri.ytdl/cache/downloads/1" -S "hasaud,acodec:aac" --embed-metadata --embed-thumbnail --convert-thumbnails "jpg" --ppa "ThumbnailsConvertor:-qmin 1 -q:v 1" --ppa "ffmpeg:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" -o "%(uploader)s - %(title)s.%(ext)s" --replace-in-metadata "video:title" ".+" "Record Video Stream | ROCKET FUN" --replace-in-metadata "video:uploader" ".+" "Radio Record" "https://www.youtube.com/live/IrDaDswZQzs?feature=shared"

Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/aes.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/__init__.py", line 78, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/Cryptodome.py", line 19, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/__init__.py", line 28, in <module>
    from Cryptodome.Cipher._mode_cbc import _create_cbc_cipher
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 45, in <module>
    raw_cbc_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_cbc", """
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_cbc': Not found '_raw_cbc.cpython-38.so', Cannot load '_raw_cbc.abi3.so': dlopen failed: cannot locate symbol "__aeabi_memcpy4" referenced by "/data/data/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_raw_cbc.abi3.so"..., Not found '_raw_cbc.so'

**Comment by zaednasr** [comment]
Closing this as its part of the yt-dlp android library bugs.
Follow here:
[https://github.com/yausername/youtubedl-android/issues/242](https://github.com/yausername/youtubedl-android/issues/242)
