### ISSUE TITLE
[BUG] App crash when downloading something

### ISSUE THREAD

**Issue by NikunjKhangwal** [deniscerri/ytdlnis#469]
**Describe the bug**
The app randomly crashed for me when downloading was going on in background

**To Reproduce**
Not sure

**Expected behavior**
Shouldn't crash

**(please complete the following information):**
 - Android Version: 12
 - App Version: 1.7.5
 - Other Device Information: Redmi 9 Android 12

**Additional context**
```
FATAL EXCEPTION: DefaultDispatcher-worker-3
Process: com.deniscerri.ytdl, PID: 11428
java.lang.RuntimeException: Only one Looper may be created per thread
	at android.os.Looper.prepare(Looper.java:119)
	at android.os.Looper.prepare(Looper.java:114)
	at com.deniscerri.ytdl.work.DownloadWorker$doWork$3$emit$4$1$4$2.invokeSuspend(SourceFile:914)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:139)
	at okio.Okio.runBlocking(SourceFile:102)
	at okio.Okio.runBlocking$default(SourceFile:3)
	at com.deniscerri.ytdl.work.DownloadWorker$doWork$3$emit$4$1.invokeSuspend(SourceFile:1227)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:96)
	at androidx.work.Worker$2.run(SourceFile:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f74b2d7, Dispatchers.IO]
```

**Comment by zaednasr** [comment]
![image](https://github.com/deniscerri/ytdlnis/assets/75589932/0d5ef8ea-4f50-4c34-b0c7-d6b8c6f56622)
looks like its hitting this piece of code. Noted

**Comment by headquarter8302** [comment]
Same issue here, same log error

**Comment by zaednasr** [comment]
I'm assuming you are downloading multiple items for this to hit correct?

**Comment by headquarter8302** [comment]
No, I was downloading a single video file, curiously. Unless the previously-failed download was queued... let me check my queue for a bit, I can't access my phone currently

**Comment by headquarter8302** [comment]
Weird, I wasn't able to replicate it, but I still support the crash to be fixed regardless

**Comment by zaednasr** [comment]
hopefully in the new update it wont happen again.

**Comment by zaednasr** [comment]
Check the latest beta:
https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.6.1-beta
