### ISSUE TITLE
[BUG] App continuously crashes after new update

### ISSUE THREAD

**Issue by NikunjKhangwal** [deniscerri/ytdlnis#512]
The app continuously keep crashing for me after new update

**Screenshots / Video Recording**
https://github.com/deniscerri/ytdlnis/assets/99175083/4692aa72-7e9b-4d5c-8afd-d6b763e29f7a

- Android Version: 12
 - App Version: 1.7.8
 - Other Device Information: Redmi 9, MIUI 13

**Additional context**
Probably happens because of database upgrade

**Logs**
`FATAL EXCEPTION: main
Process: com.deniscerri.ytdl, PID: 10790
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.deniscerri.ytdl/com.deniscerri.ytdl.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3780)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3947)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8280)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: java.lang.NullPointerException
	at com.deniscerri.ytdl.util.NavbarUtil.getStartFragmentId(Unknown Source:74)
	at com.deniscerri.ytdl.MainActivity.onCreate(SourceFile:355)
	at android.app.Activity.performCreate(Activity.java:8163)
	at android.app.Activity.performCreate(Activity.java:8130)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3753)
	... 12 more`

**Comment by tusharchopra07** [comment]
tried fresh install ?

**Comment by NikunjKhangwal** [comment]
Ok so download itself and the download card seem to work fine. Just the app isn't opening.

![Screenshot_2024-07-02-09-43-58-216_com deniscerri ytdl](https://github.com/deniscerri/ytdlnis/assets/99175083/bbc9fd4b-076f-45c3-a4c1-9293e2ea5d62)

**Comment by NikunjKhangwal** [comment]
Same thing after restoring the backup

**Comment by zaednasr** [comment]
If download card itself, opens that means its not the database fault 🤔

**Comment by zaednasr** [comment]
I know what it is, You set the preferred home screen as the download queue

**Comment by zaednasr** [comment]
send me the backup json, so i can confirm something

**Comment by NikunjKhangwal** [comment]
> I know what it is, You set the preferred home screen as the download queue

Correct, i didn't knew that's what was causing it. I mostly open the app to see the queue. Can it be fixed?

**Comment by zaednasr** [comment]
Yes, give me a bit of time, ill update the current release apk so u can get that. But fresh install it, just need to modify the json backup a bit. ill guide you
