### ISSUE TITLE
Traceback error when loading media details

### ISSUE THREAD

**Issue by ikrahul** [deniscerri/ytdlnis#611]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

Getting this error when shared the video to ytdlnis, while fetching qualities its breaking i guess.

Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 4, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp

### Expected behavior

App opens just not able to download anything.

### Steps to reproduce

Open youtube video
Click share, share to Ytdlnis
Popup opens which tries fetching qualities for video/audio and it breaks at that screen.

### Device information

Device: Samsung s24 ultra
Os: Android 14 
Oneui version: 6.1

### Screenshots / Recordings

![Screenshot_20241110_010731](https://github.com/user-attachments/assets/19ea0518-e8c9-451d-9ac0-ea60ff4edc94)

### Additional context

Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 4, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp

**Comment by deniscerri** [comment]
get version 1.8.0 of the app from this repository
