### ISSUE TITLE
[Traceback issue]

### ISSUE THREAD

**Issue by Snowball2507** [deniscerri/ytdlnis#621]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

Everytime I try downloading a video from youtube, I get traceback message.

### Expected behavior

I expected the app to download my file like it normally should.

### Steps to reproduce

1.Open app
2.Paste video url
2.Traceback message

### Device information

Samsung A52s 5G
Android 14
Qualcomm Snapdragon 778G
Octa Core
2.4 GHz

### Screenshots / Recordings

![Screenshot_20241115_215822](https://github.com/user-attachments/assets/ba440cc7-fb3c-4602-a787-a19455fe2e72)

### Additional context

Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 4, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp
![Screenshot_20241115_215822](https://github.com/user-attachments/assets/53787574-a129-41f7-87f8-1177e715fc8c)

**Comment by zaednasr** [comment]
Update to latest version
