### ISSUE TITLE
[For Android 6 Users] How to make YTDLnis usable

### ISSUE THREAD

**Issue by deniscerri** [deniscerri/ytdlnis#639]
- Download the [1.7.9.2 APK](https://github.com/deniscerri/ytdlnis/releases/tag/v1.7.9.2)
- Turn off internet on your phone
- Install the APK
- Launch ytdlnis and disable auto-updates for yt-dlp (Settings > Updating > Auto-Update yt-dlp)
- Turn internet back on
- Go to the built-in terminal in ytdlnis and run `yt-dlp -U`. This will use yt-dlp's built in updater and not the one from youtubedl-android. yt-dlp uses a lock file format to prevent updating past an incompatible python version.

Now you should have ytdlnis v1.7.9.2 with yt-dlp 2024.10.22 installed

Long term, youtubedl-android should probably be updated to either just use the built-in yt-dlp updater or support the lock file format yt-dlp uses.

_Originally posted by @seproDev in https://github.com/deniscerri/ytdlnis/issues/633#issuecomment-2495646354_

**Comment by highbaser** [comment]
Doesn't work on Android 6.0, at least on armeabi-v7. yt-dlp won't even launch after the fresh install of YTDLnis.
```~ $ yt-dlp 
Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 18, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 18, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/aes.py", line 5, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/__init__.py", line 69, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/Cryptodome.py", line 17, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/__init__.py", line 28, in <module>
    from Cryptodome.Cipher._mode_cbc import _create_cbc_cipher
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 45, in <module>
    raw_cbc_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_cbc", """
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_cbc': Not found '_raw_cbc.cpython-38.so', Cannot load '_raw_cbc.abi3.so': dlopen failed: cannot locate symbol "__aeabi_memcpy4" referenced by "/data/data/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_raw_cbc.abi3.so"..., Not found '_raw_cbc.so'```
There should be at least a **working** copy of yt-dlp to be able to update itself but there isn't any.
```
@deniscerri Why can't you just release an 1.7.9.3 which has the last Python38-compatible and working yt-dlp bundled in or can download stable@2024.10.22? Would be much more simple for everyone.

**Comment by error-reporting** [comment]
> Doesn't work on Android 6.0, at least on armeabi-v7. yt-dlp won't even launch after the fresh install of YTDLnis.
> 
> ```
> Traceback (most recent call last):
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
>   File "<frozen zipimport>", line 259, in load_module
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 18, in <module>
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/cookies.py", line 18, in <module>
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/aes.py", line 5, in <module>
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/__init__.py", line 69, in <module>
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/dependencies/Cryptodome.py", line 17, in <module>
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/__init__.py", line 28, in <module>
>     from Cryptodome.Cipher._mode_cbc import _create_cbc_cipher
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 45, in <module>
>     raw_cbc_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_cbc", """
>   File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
>     raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
> OSError: Cannot load native module 'Cryptodome.Cipher._raw_cbc': Not found '_raw_cbc.cpython-38.so', Cannot load '_raw_cbc.abi3.so': dlopen failed: cannot locate symbol "__aeabi_memcpy4" referenced by "/data/data/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/site-packages/Cryptodome/Cipher/_raw_cbc.abi3.so"..., Not found '_raw_cbc.so'```
> ```
> 
> There should be at least a **working** copy of yt-dlp to be able to update self but there isn't any.
> 
> @deniscerri Why can't you just release an 1.7.9.3 which has the last Python38-compatible and working yt-dlp bundled in or can download stable@2024.10.22? Would be much more simple for everyone.

that's not yt-dlp launch issue rather that is cryptodomex launch issue because of cryptodomex's Incompatibility of old android versions such as 6.x

**Comment by deniscerri** [comment]
As @error-reporting said this has nothing to do with yt-dlp but other support libraries not working. This is a known error on some android 6 devices since it doesnt support cryptodome.

**Comment by highbaser** [comment]
@deniscerri Is there an older version of cryptodome that would be functional on these devices?

**Comment by deniscerri** [comment]
There was a period where there was no cryptodome but that was a long time ago and the old versions of the library are not really accessible to fetch.

**Comment by error-reporting** [comment]
that don't work for me in Android 7 vm `yt-dlp -vU
[debug] Command-line config: ['--config-locations', '/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1733403218431].txt', '-P', '/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/TERMINAL/8', '--no-cache-dir', '--ffmpeg-location', '/data/app/com.deniscerri.ytdl-1/lib/arm64/libffmpeg.so']
[debug] | Config "/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1733403218431].txt": ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.4.248-hadesKernel-v2.0-greatlte-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 967, in main
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 935, in _real_main
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/update.py", line 300, in update
TypeError: remove: path should be string, bytes or os.PathLike, not NoneType`

**Comment by yosefhaylemaryam42-glitch** [comment]
Fack
