### ISSUE TITLE
Only Python versions 3.9 and above are supported by yt-dlp

### ISSUE THREAD

**Issue by PatoFlamejanteTV** [deniscerri/ytdlnis#641]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

I cant download any videos, it just show `ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp`

### Expected behavior

Download

### Steps to reproduce

1. Pick any video
2. Download 
3. Error

### Device information

Devices: Realme c55
System: Android 13

### Additional context

 -N "3" --trim-filenames "202" --no-mtime --parse-metadata "%(channel,uploader,creator,artist|null)s:%(uploader)s" --parse-metadata "%(uploader)s:%(album_artist)s" --parse-metadata "%(release_year,release_date>%Y,upload_date>%Y)s:%(meta_date)s" --parse-metadata "%(album,title)s:%(meta_album)s" --audio-quality "5" -x --audio-format "mp3" -P "/data/user/0/com.deniscerri.ytdl/cache/downloads/544" -S "hasaud,acodec:aac,ext:mp3" --embed-metadata --embed-thumbnail --convert-thumbnails "jpg" --ppa "ThumbnailsConvertor:-qmin 1 -q:v 1" --ppa "ffmpeg:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" -o "%(uploader,channel)s - %(title)s.%(ext)s" "https://youtu.be/-5ElXT3_9u4"

Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 4, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp

**Comment by deniscerri** [comment]
mate just update the app to 1.8.0...
