### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by benoyel** [deniscerri/ytdlnis#646]
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

I can't download audio or video anymore with the search bar or copied link

### Steps to reproduce

1. Use the search bar to paste your copied link
2. Select the file type you want to download, video or audio format
3. Error code show up after selecting download

### Device information

Tecno Spark 10 Pro
Android 13

### Screenshots / Recordings

Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 4, in <module>
ImportError: You are using an unsupported version of Python. Only Python versions 3.9 and above are supported by yt-dlp

**Comment by deniscerri** [comment]
get the latest version of the app
